name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquacloud-dev/github-actions/setup-node@main
      - run: pnpm install 
      - run: pnpm build
